apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: portmap
              key: port
        - name: BACKENDURL
          valueFrom:
            configMapKeyRef:
              name: urlmap
              key: backendurl
