apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: portmap
              key: port
        - name: BACKENDURL
          valueFrom:
            configMapKeyRef:
              name: urlmap
              key: backendurl

apiVersion: v1
kind: Service
metadata:
  name: frontend-port
spec:
  selector:
    app: front
  ports:
  - port: 8080

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
spec:
  host: frontend-port-k8s-final-drill-roy.apps.uwtd7zko.eastus.aroapp.io
  path: "/front" 
  to:
    kind: Service
    name: frontend-port
