apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:backend
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: portmap
              key: port
        volumeMounts:
        - mountPath: "/tmp/persistent"
          name: persistent-volume
        - mountPath: "/tmp/ephemeral"
          name: ephemeral-volume
      volumes:
      - name: persistent-volume
        persistentVolumeClaim:
          claimName: persistent-claim
      - name: ephemeral-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "scratch-storage-class"
            resources:
              requests:
                storage: 1Gi

apiVersion: v1
kind: Service
metadata:
  name: backend-port
spec:
  selector:
    app: back
  ports:
  - port: 8080
